language: rust
rust:
  - nightly
  - beta
  - stable
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose --features ci
  - cargo doc
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
notifications:
  email:
    on_success: never
