[package]

name = "semver"
version = "0.6.0"
authors = ["Steve Klabnik <steve@steveklabnik.com>", "The Rust Project Developers"]
license = "MIT/Apache-2.0"
repository = "https://github.com/steveklabnik/semver"
homepage = "https://docs.rs/crate/semver/"
documentation = "https://docs.rs/crate/semver/"
description = """
Semantic version parsing and comparison.
"""

[dependencies]
semver-parser = "0.7.0"

# Serde (SERialization & DEserialization)
serde = { version = "0.9.13", optional = true }
# Allows for use of the derive macro for the [De]Serialize trait
serde_derive = { version = "0.9.13", optional = true }

[features]
default = []

# are we testing on CI?
ci = []

# do we want serde support? we need the library
serde_support = ["serde", "serde_derive"]

[dev-dependencies]
crates-index = "0.5.0"
tempdir = "0.3.4"
