[package]

name = "semver"
version = "0.1.3"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-lang/semver"
homepage = "https://github.com/rust-lang/semver"
description = """
Semantic version parsing and comparison.
"""
